export enum RaceStatus {
  DRAFT = 'DRAFT',
  OPEN_FOR_REGISTRATION = 'OPEN_FOR_REGISTRATION',
  CLOSED = 'CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
